import { Appearance, useColorScheme } from 'react-native';

const COLOR = {
  BRAND: '#F58C22',
  BRAND_LIGHT: '#ffbd55',
  BRAND_DARK: '#bc5e00',
  ACCENT: '#2e7d32',
  WHITE: '#FFFFFF',
  WHITE_BRIGHT: '#fafafa',
  WHITE_LIGHT: '#f7f7f7',
  BLACK: '#161616',
  BLACK_DARK: '#000000',
  BLACK_LIGHT: '#1e1e1e',
  DARK_BLACK: '#2d2d2d',
  DARK: '#333333',
  GRAY: '#777777',
  GRAY_LIGHT: '#cdcdcd',
  GREY: '#656565',
  GREY_LIGHT: '#999999',
  GREY_BRIGHT: '#e1e1e1',
  GREY_DARK: '#5c5c5c',
  RED: '#d9534f',
  ORANGE: '#ff8f00',
  GREEN: '#60d517',
  BLUE: '#0091ea',
  PINK: '#d81b60',
  YELLOW: '#fdd835',
  RED_DARK: '#c62828',
  ORANGE_DARK: '#ff6f00',
  GREEN_DARK: '#00875a',
  BLUE_DARK: '#5e98d8',
  PINK_DARK: '#b4004e',
  YELLOW_DARK: '#ffa000',
  NEUTRAL: 'rgba(255,255,255, 0.65)',
};

export const COMPONENTS = {
  TRANSPARENT: 'transparent',
  NEUTRAL: COLOR.NEUTRAL,
};

const DARK_COMPONENTS = {
  ...COMPONENTS,
  FACEBOOK: '#4188cd',
  LOGIN: '#e3ae3e',
  PRIMARY: COLOR.BRAND,
  PRIMARY_LIGHT: COLOR.BRAND_LIGHT,
  INFO: COLOR.BLUE_DARK,
  DANGER: COLOR.RED_DARK,
  WARNING: COLOR.ORANGE_DARK,
  SUCCESS: COLOR.GREEN_DARK,
  BUTTON: COLOR.BRAND,
  LINK: COLOR.BLUE_DARK,
  TEXT: COLOR.GRAY_LIGHT,
  TEXT_DARK: COLOR.WHITE_LIGHT,
  TEXT_LIGHT: COLOR.WHITE_BRIGHT,
  BACKGROUND: COLOR.BLACK,
  BACKGROUND_LIGHT: COLOR.BLACK_LIGHT,
  BACKGROUND_DARK: COLOR.BLACK_DARK,
  BACKGROUND_GREY: COLOR.DARK_BLACK,
  BORDER: COLOR.DARK,
  BORDER_LIGHT: COLOR.DARK_BLACK,
  INPUT: COLOR.GRAY_LIGHT,
  PLACEHOLDER: COLOR.GREY_LIGHT,
  NAVBAR: COLOR.WHITE_LIGHT,
  BLOCK: COLOR.GREY,
  ICON: COLOR.GRAY_LIGHT,
  ICON_LIGHT: COLOR.GRAY_LIGHT,
  SHADOW: COLOR.DARK,
  DISABLED: COLOR.GRAY_LIGHT,
  INVERSE_BG: COLOR.GRAY_LIGHT,
  INVERSE_TEXT: COLOR.WHITE_LIGHT,
  LOADER: COLOR.WHITE_BRIGHT,
};

const LIGHT_COMPONENTS = {
  ...COMPONENTS,
  FACEBOOK: '#1778f2',
  LOGIN: '#ff5253',
  PRIMARY: COLOR.BRAND,
  PRIMARY_LIGHT: COLOR.BRAND_LIGHT,
  INFO: COLOR.BLUE,
  DANGER: COLOR.RED,
  WARNING: COLOR.ORANGE,
  SUCCESS: COLOR.GREEN,
  BUTTON: COLOR.BRAND,
  LINK: COLOR.BLUE,
  TEXT: COLOR.GREY_DARK,
  TEXT_DARK: COLOR.DARK,
  TEXT_LIGHT: COLOR.GREY,
  BACKGROUND: COLOR.WHITE,
  BACKGROUND_LIGHT: COLOR.WHITE_LIGHT,
  BACKGROUND_DARK: COLOR.GRAY_LIGHT,
  BACKGROUND_GREY: COLOR.WHITE_LIGHT,
  BORDER: COLOR.GREY,
  BORDER_LIGHT: COLOR.GREY_BRIGHT,
  INPUT: COLOR.GREY,
  PLACEHOLDER: COLOR.GREY_LIGHT,
  NAVBAR: COLOR.WHITE_LIGHT,
  BLOCK: COLOR.GREY,
  ICON: COLOR.DARK,
  ICON_LIGHT: COLOR.GREY_DARK,
  SHADOW: COLOR.DARK,
  DISABLED: COLOR.GRAY_LIGHT,
  INVERSE_BG: COLOR.BLACK_DARK,
  INVERSE_TEXT: COLOR.DARK,
  LOADER: COLOR.GREY_BRIGHT,
};

let MODE: any = 'light';

export const setTheme = (
  mode = useColorScheme(),
  DARK = DARK_COMPONENTS,
  LIGHT = LIGHT_COMPONENTS
) => {
  var colors = mode === 'dark' ? DARK : LIGHT;
  if (MODE !== mode) {
    COLORS = colors;
    MODE = mode;
  }
  return colors;
};

var COLORS = setTheme(MODE);

export { COLORS, MODE };

export default COLORS;
